version: "3.3"
services:
  ## build edumeet-room-server
  edumeet-room-server:
    env_file: .env
    restart: unless-stopped
    volumes:
      - ${PWD}/configs/server:/usr/src/app/dist/config
      - ${PWD}/certs:/usr/src/app/certs
    container_name: edumeet-room-server
    #image: ${REPOSITORY}/${EDUMEET_SERVER}-room-server:${TAG}
    # Comment out whole build-section to build edumeet-room-server and not pulling from docher-hub
    build:
      args:
        - GIT_SERVER=${GIT_SERVER}
        - REPOSITORY=${REPOSITORY}
        - EDUMEET_SERVER=${EDUMEET_SERVER}
        - BRANCH_SERVER=${BRANCH_SERVER}
        - BRANCH_MN_SERVER_SECRET=${BRANCH_MN_SERVER_SECRET}
      context: .
      dockerfile: Dockerfile-server
    image: ${REPOSITORY}/${EDUMEET_SERVER}:${TAG}
    ## use host mode for the media ports
    network_mode: "host"
    stdin_open: true
    tty: true

  ## build edumeet-client instance + web proxy
  edumeet-client:
    env_file: .env
    volumes:
      - ${PWD}/configs/app:/usr/share/nginx/html/config
      - ${PWD}/configs/nginx:/etc/nginx/conf.d
      - ${PWD}/certs:/etc/edumeet/certs
    container_name: edumeet-client
    #image: ${REPOSITORY}/${EDUMEET_CLIENT}:${TAG}
    # Comment out whole build-section to build edumeet-room-server and not pulling from docher-hub
    build:
      args:
        - GIT_SERVER=${GIT_SERVER}
        - REPOSITORY=${REPOSITORY}
        - EDUMEET_CLIENT=${EDUMEET_CLIENT}
        - BRANCH_CLIENT=${BRANCH_CLIENT}
      context: .
      dockerfile: Dockerfile-client
    image: ${REPOSITORY}/${EDUMEET_CLIENT}:${TAG}
    ports:
        - "80:80"
        - "443:443"
        ## build edumeet-client instance + web proxy
  edumeet-media-node:
    env_file: .env
    volumes:
      - ${PWD}/configs/app:/usr/share/nginx/html/config
    container_name: edumeet-media-node
    #image: ${REPOSITORY}/${EDUMEET_CLIENT}:${TAG}
    # Comment out whole build-section to build edumeet-room-server and not pulling from docher-hub
    build:
      args:
        - GIT_SERVER=${GIT_SERVER}
        - REPOSITORY=${REPOSITORY}
        - EDUMEET_MN_SERVER=${EDUMEET_MN_SERVER}
        - BRANCH_MN_SERVER=${BRANCH_MN_SERVER}
      context: .
      dockerfile: Dockerfile-medianode
    image: ${REPOSITORY}/${EDUMEET_MN_SERVER}:${TAG}
    ports:
        - "3000:3000"
  # build edumeet-translator instance
 # edumeet-translator:
 #   env_file: .env
 #   container_name: edumeet-translator
 #   #image: ${REPOSITORY}/edumeet-translator:${TAG}
 #   ## TODO
 #   build:
 #     args:
 #       - BASEDIR=${BASEDIR}
 #       - GIT_SERVER=${GIT_SERVER}
 #       - REPOSITORY=${REPOSITORY}
 #       - EDUMEET_CLIENT=${EDUMEET_CLIENT}
 #       - BRANCH_CLIENT=${BRANCH_CLIENT}
 #     context: .
 #     dockerfile: Dockerfile-translator
 #   ports:
 #       - "8080:80"
