version: '3.3'
services:
  edumeet-room-server:
    env_file: .env
    restart: unless-stopped
    volumes:
      - './configs/server:/usr/src/app/dist/config'
      # If running separately and you need certs
      # - ./certs:/usr/src/app/certs
    container_name: edumeet-room-server
    # Comment out whole build-section to build edumeet-room-server and not pulling from docher-hub
    build:
      args:
        - 'GIT_SERVER=${GIT_SERVER}'
        - 'REPOSITORY=${REPOSITORY}'
        - 'EDUMEET_SERVER=${EDUMEET_SERVER}'
        - 'BRANCH_SERVER=${BRANCH_SERVER}'
        - 'SERVER_MANAGEMENT_PASSWORD=${SERVER_MANAGEMENT_PASSWORD}'
        - 'SERVER_MANAGEMENT_USERNAME=${SERVER_MANAGEMENT_USERNAME}'
        
      context: .
      dockerfile: Dockerfiles/Dockerfile-room-server
    image: '${REPOSITORY}/${EDUMEET_SERVER}:${TAG}'
    links:
     - "edumeet-management-server:mgmt"
    ports:
      - '8443:8443'
  edumeet-client:
    env_file: .env
    volumes:
      - './configs/app:/usr/share/nginx/html/config'
      - './images/logo.edumeet.svg:/usr/share/nginx/html/images/logo.edumeet.svg'
      - './configs/nginx:/etc/nginx/conf.d'
      - './certs:/etc/edumeet/certs'
    links:
     - "edumeet-management-client:emc"
     - "keycloak:kc"
     - "edumeet-room-server:io"
     - "edumeet-management-server:mgmt"
    # - "pgadmin:pgadmin"
    container_name: edumeet-client
    build:
      args:
        - 'GIT_SERVER=${GIT_SERVER}'
        - 'REPOSITORY=${REPOSITORY}'
        - 'EDUMEET_CLIENT=${EDUMEET_CLIENT}'
        - 'BRANCH_CLIENT=${BRANCH_CLIENT}'
      context: .
      dockerfile: Dockerfiles/Dockerfile-client
    image: '${REPOSITORY}/${EDUMEET_CLIENT}:${TAG}'
    ports:
      - '80:80'
      - '443:443'
      - '3002:3002'
#      - '8443:8443'
  edumeet-media-node:
    env_file: .env
    volumes:
      - './certs:/usr/src/app/certs'
    container_name: edumeet-media-node
    build:
      args:
        - 'GIT_SERVER=${GIT_SERVER}'
        - 'REPOSITORY=${REPOSITORY}'
        - 'EDUMEET_MN_SERVER=${EDUMEET_MN_SERVER}'
        - 'BRANCH_MN_SERVER=${BRANCH_MN_SERVER}'
        - 'MN_IP=${MN_IP}'
        - 'MN_EXTRA_PARAMS=${MN_EXTRA_PARAMS}'
      context: .
      dockerfile: Dockerfiles/Dockerfile-media-node
    image: '${REPOSITORY}/${EDUMEET_MN_SERVER}:${TAG}'
    security_opt:
      - seccomp:unconfined
    network_mode: "host"
#    ports:
#      - '40000-40249:40000-40249'
#      - '3000:3000'
  edumeet-db:
    env_file: .env
    image: 'postgres:14.1-alpine'
    container_name: edumeet-db
    restart: always
    volumes:
      - 'edumeet-db:/var/lib/postgresql/data'
  edumeet-management-server:
    env_file: .env
    container_name: edumeet-management-server
    volumes:
      - './configs/mgmt:/usr/src/app/config'
      - './configs/_mgmt_pwchange/202310300000000_migrate.ts:/usr/src/app/migrations/202310300000000_migrate.ts'
    build:
      args:
        - 'GIT_SERVER=${GIT_SERVER}'
        - 'REPOSITORY=${REPOSITORY}'
        - 'EDUMEET_MGMT_SERVER=${EDUMEET_MGMT_SERVER}'
        - 'BRANCH_MGMT_SERVER=${BRANCH_MGMT_SERVER}'
        - 'NODE_TLS_REJECT_UNAUTHORIZED=${NODE_TLS_REJECT_UNAUTHORIZED}'
      context: .
      dockerfile: Dockerfiles/Dockerfile-management-server
    image: '${REPOSITORY}/${EDUMEET_MGMT_SERVER}:${TAG}'
#    ports:
#      - '3030:3030'
    depends_on:
      - edumeet-db
#  pgadmin:
#    env_file: .env
#    image: dpage/pgadmin4
#    container_name: pgadmin4_container
#    restart: always
    #ports:
    #  - '5050:80'
#    volumes:
#      - 'edumeet-db-data:/var/lib/pgadmin'
  keycloak:
    env_file: .env
    container_name: edumeet_keycloak
    volumes:
      - './certs:/opt/keycloak/conf'
      - './configs/kc:/opt/keycloak/data/import'
    image: 'quay.io/keycloak/keycloak:latest'
    command:
      - start
      #- '--auto-build'
      - '--import-realm'
    # ports:
    #   - '8080:8080'
    #   - '8443:8443'
    restart: unless-stopped
  edumeet-management-client:
    env_file: .env
    container_name: edumeet-management-client
    volumes:
      - ./configs/mgmt-client:/usr/src/app/public/config
    build:
      args:
        - GIT_SERVER=${GIT_SERVER}
        - REPOSITORY=${REPOSITORY}
        - EDUMEET_MGMT_CLIENT=${EDUMEET_MGMT_CLIENT}
        - BRANCH_MGMT_CLIENT=${BRANCH_MGMT_CLIENT}
        - PUBLIC_URL=${PUBLIC_URL}
      context: .
      dockerfile: Dockerfiles/Dockerfile-management-client
    image: ${REPOSITORY}/${EDUMEET_MGMT_CLIENT}:${TAG}
    #ports:
    #    - "3001:3000"
  #edumeet-translator:
  #   env_file: .env
  #   container_name: edumeet-translator
  #   build:
  #      args:
  #       - BASEDIR=${BASEDIR}
  #       - GIT_SERVER=${GIT_SERVER}
  #       - REPOSITORY=${REPOSITORY}
  #       - EDUMEET_CLIENT=${EDUMEET_CLIENT}
  #       - BRANCH_CLIENT=${BRANCH_CLIENT}
  #      context: .
  #      dockerfile: Dockerfiles/Dockerfile-translator
  #   image: ${REPOSITORY}/edumeet-translator:${TAG}
volumes:
  edumeet-db:
    driver: local
  edumeet-db-data:
    driver: local
