version: "3.3"

services:
# edumeet
  edumeet:
    env_file: .env
    image: ${REPOSITORY}/${EDUMEET}:${TAG}
    depends_on: 
      - redis
    restart: unless-stopped
    volumes:
      - ${PWD}/configs/server:${BASEDIR}/${EDUMEET}/server/dist/config
      - ${PWD}/configs/app:${BASEDIR}/${EDUMEET}/server/dist/public/config
      - ${PWD}/certs:${BASEDIR}/${EDUMEET}/server/certs
      - ${PWD}/images:${BASEDIR}/${EDUMEET}/server/dist/public/images
      - ${PWD}/privacy:${BASEDIR}/${EDUMEET}/server/dist/public/static/privacy
      - ${PWD}/.well-known:${BASEDIR}/${EDUMEET}/server/dist/public/.well-known
    network_mode: "host"
    stdin_open: true
    tty: true
#   environment:
#     - DEBUG=edumeet*

  redis:
    image: redis
    network_mode: "host"
    entrypoint: redis-server /usr/local/etc/redis/redis.conf
    restart: unless-stopped
    volumes:
      - ${PWD}/configs/redis:/usr/local/etc/redis

# Uncomment "ouroboros" image and change timezone (TZ) if you require automatic docker image update

#  ouroboros:
#    container_name: ouroboros
#    hostname: ouroboros
#    image: pyouroboros/ouroboros
#    environment:
#      - CLEANUP=true
#      - INTERVAL=300
#      - LOG_LEVEL=info
#      - SELF_UPDATE=true
#      - IGNORE=mongo influxdb postgres mariadb
#      - TZ=Europe/Budapest
#      - CRON="* 2 * * *"
#    restart: unless-stopped
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
