version: "3.7"

services:
# multiparty-meeting
  mm:
    env_file: .env
    image: misi/mm:${TAG}
    depends_on: 
      - redis
    build:
      args:
        - BASEDIR=${BASEDIR}
        - MM=${MM}
        - NODE_ENV=${NODE_ENV}
        - SERVER_DEBUG=${SERVER_DEBUG}
      context: ./
    restart: always
    volumes:
      - ${PWD}/configs/server:${BASEDIR}/${MM}/server/config
      - ${PWD}/configs/app:${BASEDIR}/${MM}/server/public/config
      - ${PWD}/certs:${BASEDIR}/${MM}/server/certs
      - ${PWD}/images:${BASEDIR}/${MM}/server/public/images
    ports:
      - "80:80"
      - "443:443"
      - "40000-49999:40000-49999/udp"
    network_mode: "host"
    stdin_open: true
    tty: true

  redis:
    image: redis
    network_mode: "host"
    entrypoint: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ${PWD}/configs/redis:/usr/local/etc/redis
